name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill in the details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Is your feature request related to a problem? What are you trying to achieve?
      placeholder: I'm trying to build a reading app and I need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see. What would the API look like?
      placeholder: |
        I'd like a `curlRadius` parameter in PageCurlContainer:
        ```kotlin
        PageCurlContainer(
            pages = ...,
            curlRadius = 0.12f,   // new parameter
        )
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references (e.g., iOS API equivalents).

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests before filing this one.
          required: true
